#
# Copyright (c) 2023 iWorx Systems Inc.
#
# SPDX-License-Identifier: BSD-Protection
#

manifest:
  remotes:
    - name: antmicro
      url-base: https://github.com/antmicro
    - name: scottl_private
      url-base: git@github.com:scottlaboe
    - name: scottl_public
      url-base: https://github.com/scottlaboe

  projects:
    # Zephyr
    - name: zephyr
      remote: scottl_public
      revision: main
      import:
        path-prefix: zephyr_project
        name-allowlist:
          - hal_nuvoton
          - cmsis
          - segger
          - tinycrypt
          - mcuboot

    # Cmock/Unity module
    - name: test
      remote: antmicro
      revision: main
      repo-path: zephyr-cmock-unity-module
      import: true

    # Boards
    - name: iworx-zephyr-boards
      remote: scottl_private
      repo-path: iworx-zephyr-boards.git
      revision: main

    # Drivers
    - name: iworx-zephyr-drivers
      remote: scottl_private
      repo-path: iworx-zephyr-drivers.git
      revision: main

  self:
    path: Zephyr-Dev-Container-Template